/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a /tmp/ws_adaptor -c WallpaperServiceAdaptor daemon/src/ipc/wallpaper_service.xml
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "wallpaper_service_adaptor.h"
#include <QMetaObject>
#include <QByteArray>
#include <QList>
#include <QMap>
#include <QString>
#include <QStringList>
#include <QVariant>

/*
 * Implementation of adaptor class WallpaperServiceAdaptor
 */

WallpaperServiceAdaptor::WallpaperServiceAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

WallpaperServiceAdaptor::~WallpaperServiceAdaptor()
{
    // destructor
}

void WallpaperServiceAdaptor::addCustomLibraryPath(const QString &in0)
{
    // handle method call org.plasmawallpaperengine.Daemon.addCustomLibraryPath
    QMetaObject::invokeMethod(parent(), "addCustomLibraryPath", Q_ARG(QString, in0));
}

double WallpaperServiceAdaptor::getAudioBands()
{
    // handle method call org.plasmawallpaperengine.Daemon.getAudioBands
    double out0;
    QMetaObject::invokeMethod(parent(), "getAudioBands", Q_RETURN_ARG(double, out0));
    return out0;
}

QVariantMap WallpaperServiceAdaptor::getAudioSettings()
{
    // handle method call org.plasmawallpaperengine.Daemon.getAudioSettings
    QVariantMap out0;
    QMetaObject::invokeMethod(parent(), "getAudioSettings", Q_RETURN_ARG(QVariantMap, out0));
    return out0;
}

QVariantList WallpaperServiceAdaptor::getAvailableGpus()
{
    // handle method call org.plasmawallpaperengine.Daemon.getAvailableGpus
    QVariantList out0;
    QMetaObject::invokeMethod(parent(), "getAvailableGpus", Q_RETURN_ARG(QVariantList, out0));
    return out0;
}

void WallpaperServiceAdaptor::getBufferFdForOutput(const QString &in0)
{
    // handle method call org.plasmawallpaperengine.Daemon.getBufferFdForOutput
    QMetaObject::invokeMethod(parent(), "getBufferFdForOutput", Q_ARG(QString, in0));
}

QVariantMap WallpaperServiceAdaptor::getBufferInfo()
{
    // handle method call org.plasmawallpaperengine.Daemon.getBufferInfo
    QVariantMap out0;
    QMetaObject::invokeMethod(parent(), "getBufferInfo", Q_RETURN_ARG(QVariantMap, out0));
    return out0;
}

QVariantMap WallpaperServiceAdaptor::getBufferInfoForOutput(const QString &in0)
{
    // handle method call org.plasmawallpaperengine.Daemon.getBufferInfoForOutput
    QVariantMap out0;
    QMetaObject::invokeMethod(parent(), "getBufferInfoForOutput", Q_RETURN_ARG(QVariantMap, out0), Q_ARG(QString, in0));
    return out0;
}

QVariantList WallpaperServiceAdaptor::getLibrary()
{
    // handle method call org.plasmawallpaperengine.Daemon.getLibrary
    QVariantList out0;
    QMetaObject::invokeMethod(parent(), "getLibrary", Q_RETURN_ARG(QVariantList, out0));
    return out0;
}

QStringList WallpaperServiceAdaptor::getOutputs()
{
    // handle method call org.plasmawallpaperengine.Daemon.getOutputs
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "getOutputs", Q_RETURN_ARG(QStringList, out0));
    return out0;
}

QVariantList WallpaperServiceAdaptor::getPauseState()
{
    // handle method call org.plasmawallpaperengine.Daemon.getPauseState
    QVariantList out0;
    QMetaObject::invokeMethod(parent(), "getPauseState", Q_RETURN_ARG(QVariantList, out0));
    return out0;
}

QDBusVariant WallpaperServiceAdaptor::getProperty(const QString &in0)
{
    // handle method call org.plasmawallpaperengine.Daemon.getProperty
    QDBusVariant out0;
    QMetaObject::invokeMethod(parent(), "getProperty", Q_RETURN_ARG(QDBusVariant, out0), Q_ARG(QString, in0));
    return out0;
}

QStringList WallpaperServiceAdaptor::getTrustedDirectories()
{
    // handle method call org.plasmawallpaperengine.Daemon.getTrustedDirectories
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "getTrustedDirectories", Q_RETURN_ARG(QStringList, out0));
    return out0;
}

QVariantMap WallpaperServiceAdaptor::getWallpaperProperties(const QString &in0)
{
    // handle method call org.plasmawallpaperengine.Daemon.getWallpaperProperties
    QVariantMap out0;
    QMetaObject::invokeMethod(parent(), "getWallpaperProperties", Q_RETURN_ARG(QVariantMap, out0), Q_ARG(QString, in0));
    return out0;
}

bool WallpaperServiceAdaptor::isOutputCovered(const QString &in0)
{
    // handle method call org.plasmawallpaperengine.Daemon.isOutputCovered
    bool out0;
    QMetaObject::invokeMethod(parent(), "isOutputCovered", Q_RETURN_ARG(bool, out0), Q_ARG(QString, in0));
    return out0;
}

bool WallpaperServiceAdaptor::isPauseAllOutputs()
{
    // handle method call org.plasmawallpaperengine.Daemon.isPauseAllOutputs
    bool out0;
    QMetaObject::invokeMethod(parent(), "isPauseAllOutputs", Q_RETURN_ARG(bool, out0));
    return out0;
}

bool WallpaperServiceAdaptor::isPauseEnabled()
{
    // handle method call org.plasmawallpaperengine.Daemon.isPauseEnabled
    bool out0;
    QMetaObject::invokeMethod(parent(), "isPauseEnabled", Q_RETURN_ARG(bool, out0));
    return out0;
}

bool WallpaperServiceAdaptor::isPauseMuteAudio()
{
    // handle method call org.plasmawallpaperengine.Daemon.isPauseMuteAudio
    bool out0;
    QMetaObject::invokeMethod(parent(), "isPauseMuteAudio", Q_RETURN_ARG(bool, out0));
    return out0;
}

bool WallpaperServiceAdaptor::loadWallpaper(const QString &in0)
{
    // handle method call org.plasmawallpaperengine.Daemon.loadWallpaper
    bool out0;
    QMetaObject::invokeMethod(parent(), "loadWallpaper", Q_RETURN_ARG(bool, out0), Q_ARG(QString, in0));
    return out0;
}

void WallpaperServiceAdaptor::pause()
{
    // handle method call org.plasmawallpaperengine.Daemon.pause
    QMetaObject::invokeMethod(parent(), "pause");
}

double WallpaperServiceAdaptor::pauseCoverageThreshold()
{
    // handle method call org.plasmawallpaperengine.Daemon.pauseCoverageThreshold
    double out0;
    QMetaObject::invokeMethod(parent(), "pauseCoverageThreshold", Q_RETURN_ARG(double, out0));
    return out0;
}

bool WallpaperServiceAdaptor::registerTrustedDirectory(const QString &in0)
{
    // handle method call org.plasmawallpaperengine.Daemon.registerTrustedDirectory
    bool out0;
    QMetaObject::invokeMethod(parent(), "registerTrustedDirectory", Q_RETURN_ARG(bool, out0), Q_ARG(QString, in0));
    return out0;
}

void WallpaperServiceAdaptor::requestFrame()
{
    // handle method call org.plasmawallpaperengine.Daemon.requestFrame
    QMetaObject::invokeMethod(parent(), "requestFrame");
}

void WallpaperServiceAdaptor::resume()
{
    // handle method call org.plasmawallpaperengine.Daemon.resume
    QMetaObject::invokeMethod(parent(), "resume");
}

void WallpaperServiceAdaptor::scanLibrary()
{
    // handle method call org.plasmawallpaperengine.Daemon.scanLibrary
    QMetaObject::invokeMethod(parent(), "scanLibrary");
}

void WallpaperServiceAdaptor::setAudioMuted(bool in0)
{
    // handle method call org.plasmawallpaperengine.Daemon.setAudioMuted
    QMetaObject::invokeMethod(parent(), "setAudioMuted", Q_ARG(bool, in0));
}

void WallpaperServiceAdaptor::setAudioVolume(int in0)
{
    // handle method call org.plasmawallpaperengine.Daemon.setAudioVolume
    QMetaObject::invokeMethod(parent(), "setAudioVolume", Q_ARG(int, in0));
}

void WallpaperServiceAdaptor::setMousePosition(double in0, double in1)
{
    // handle method call org.plasmawallpaperengine.Daemon.setMousePosition
    QMetaObject::invokeMethod(parent(), "setMousePosition", Q_ARG(double, in0), Q_ARG(double, in1));
}

void WallpaperServiceAdaptor::setMuteOnFullscreen(bool in0)
{
    // handle method call org.plasmawallpaperengine.Daemon.setMuteOnFullscreen
    QMetaObject::invokeMethod(parent(), "setMuteOnFullscreen", Q_ARG(bool, in0));
}

void WallpaperServiceAdaptor::setMuteOnOtherAudio(bool in0)
{
    // handle method call org.plasmawallpaperengine.Daemon.setMuteOnOtherAudio
    QMetaObject::invokeMethod(parent(), "setMuteOnOtherAudio", Q_ARG(bool, in0));
}

void WallpaperServiceAdaptor::setPauseAllOutputs(bool in0)
{
    // handle method call org.plasmawallpaperengine.Daemon.setPauseAllOutputs
    QMetaObject::invokeMethod(parent(), "setPauseAllOutputs", Q_ARG(bool, in0));
}

void WallpaperServiceAdaptor::setPauseCoverageThreshold(double in0)
{
    // handle method call org.plasmawallpaperengine.Daemon.setPauseCoverageThreshold
    QMetaObject::invokeMethod(parent(), "setPauseCoverageThreshold", Q_ARG(double, in0));
}

void WallpaperServiceAdaptor::setPauseEnabled(bool in0)
{
    // handle method call org.plasmawallpaperengine.Daemon.setPauseEnabled
    QMetaObject::invokeMethod(parent(), "setPauseEnabled", Q_ARG(bool, in0));
}

void WallpaperServiceAdaptor::setPauseMuteAudio(bool in0)
{
    // handle method call org.plasmawallpaperengine.Daemon.setPauseMuteAudio
    QMetaObject::invokeMethod(parent(), "setPauseMuteAudio", Q_ARG(bool, in0));
}

void WallpaperServiceAdaptor::setProperty(const QString &in0, const QDBusVariant &in1)
{
    // handle method call org.plasmawallpaperengine.Daemon.setProperty
    QMetaObject::invokeMethod(parent(), "setProperty", Q_ARG(QString, in0), Q_ARG(QDBusVariant, in1));
}

bool WallpaperServiceAdaptor::setResolution(uint in0, uint in1)
{
    // handle method call org.plasmawallpaperengine.Daemon.setResolution
    bool out0;
    QMetaObject::invokeMethod(parent(), "setResolution", Q_RETURN_ARG(bool, out0), Q_ARG(uint, in0), Q_ARG(uint, in1));
    return out0;
}

bool WallpaperServiceAdaptor::setResolutionForOutput(const QString &in0, uint in1, uint in2)
{
    // handle method call org.plasmawallpaperengine.Daemon.setResolutionForOutput
    bool out0;
    QMetaObject::invokeMethod(parent(), "setResolutionForOutput", Q_RETURN_ARG(bool, out0), Q_ARG(QString, in0), Q_ARG(uint, in1), Q_ARG(uint, in2));
    return out0;
}

bool WallpaperServiceAdaptor::startAudioCapture()
{
    // handle method call org.plasmawallpaperengine.Daemon.startAudioCapture
    bool out0;
    QMetaObject::invokeMethod(parent(), "startAudioCapture", Q_RETURN_ARG(bool, out0));
    return out0;
}

void WallpaperServiceAdaptor::stop()
{
    // handle method call org.plasmawallpaperengine.Daemon.stop
    QMetaObject::invokeMethod(parent(), "stop");
}

void WallpaperServiceAdaptor::stopAudioCapture()
{
    // handle method call org.plasmawallpaperengine.Daemon.stopAudioCapture
    QMetaObject::invokeMethod(parent(), "stopAudioCapture");
}

