/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a /tmp/fd_adaptor -c WallpaperServiceAdaptor daemon/src/ipc/wallpaper_service.xml
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef WS_ADAPTOR_H
#define WS_ADAPTOR_H

#include <QObject>
#include <QtDBus/QtDBus>


/*
 * Adaptor class for interface org.plasmawallpaperengine.Daemon
 */
class WallpaperServiceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.plasmawallpaperengine.Daemon")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.plasmawallpaperengine.Daemon\">\n"
"    <method name=\"getBufferInfo\">\n"
"      <annotation value=\"WallpaperService::getBufferInfo\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"a{sv}\"/>\n"
"    </method>\n"
"    <method name=\"loadWallpaper\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <annotation value=\"WallpaperService::loadWallpaper\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"loadWallpaperEphemeral\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <annotation value=\"WallpaperService::loadWallpaperEphemeral\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"requestFrame\">\n"
"      <annotation value=\"WallpaperService::requestFrame\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"setResolution\">\n"
"      <arg direction=\"in\" type=\"u\"/>\n"
"      <arg direction=\"in\" type=\"u\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <annotation value=\"WallpaperService::setResolution\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"getAvailableGpus\">\n"
"      <annotation value=\"QVariantList\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"a{sv}\"/>\n"
"      <annotation value=\"WallpaperService::getAvailableGpus\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"setResolutionForOutput\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"u\"/>\n"
"      <arg direction=\"in\" type=\"u\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <annotation value=\"WallpaperService::setResolutionForOutput\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"getBufferFdForOutput\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"h\"/>\n"
"      <annotation value=\"WallpaperService::getBufferFdForOutput\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"getBufferInfoForOutput\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"a{sv}\"/>\n"
"      <annotation value=\"WallpaperService::getBufferInfoForOutput\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"getOutputs\">\n"
"      <annotation value=\"QStringList\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"as\"/>\n"
"      <annotation value=\"WallpaperService::getOutputs\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"setMousePosition\">\n"
"      <arg direction=\"in\" type=\"d\"/>\n"
"      <arg direction=\"in\" type=\"d\"/>\n"
"      <annotation value=\"WallpaperService::setMousePosition\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"setPauseEnabled\">\n"
"      <arg direction=\"in\" type=\"b\"/>\n"
"      <annotation value=\"WallpaperService::setPauseEnabled\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"setPauseAllOutputs\">\n"
"      <arg direction=\"in\" type=\"b\"/>\n"
"      <annotation value=\"WallpaperService::setPauseAllOutputs\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"setPauseCoverageThreshold\">\n"
"      <arg direction=\"in\" type=\"d\"/>\n"
"      <annotation value=\"WallpaperService::setPauseCoverageThreshold\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"setPauseMuteAudio\">\n"
"      <arg direction=\"in\" type=\"b\"/>\n"
"      <annotation value=\"WallpaperService::setPauseMuteAudio\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"isPauseEnabled\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <annotation value=\"WallpaperService::isPauseEnabled\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"isPauseAllOutputs\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <annotation value=\"WallpaperService::isPauseAllOutputs\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"pauseCoverageThreshold\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"      <annotation value=\"WallpaperService::pauseCoverageThreshold\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"isPauseMuteAudio\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <annotation value=\"WallpaperService::isPauseMuteAudio\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"isOutputCovered\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <annotation value=\"WallpaperService::isOutputCovered\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"getPauseState\">\n"
"      <annotation value=\"QVariantList\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"a{sv}\"/>\n"
"      <annotation value=\"WallpaperService::getPauseState\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"startAudioCapture\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <annotation value=\"WallpaperService::startAudioCapture\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"stopAudioCapture\">\n"
"      <annotation value=\"WallpaperService::stopAudioCapture\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"getAudioBands\">\n"
"      <annotation value=\"QVariantList\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"av\"/>\n"
"      <annotation value=\"WallpaperService::getAudioBands\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"setAudioVolume\">\n"
"      <arg direction=\"in\" type=\"i\"/>\n"
"      <annotation value=\"WallpaperService::setAudioVolume\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"setAudioMuted\">\n"
"      <arg direction=\"in\" type=\"b\"/>\n"
"      <annotation value=\"WallpaperService::setAudioMuted\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"setMuteOnOtherAudio\">\n"
"      <arg direction=\"in\" type=\"b\"/>\n"
"      <annotation value=\"WallpaperService::setMuteOnOtherAudio\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"setMuteOnFullscreen\">\n"
"      <arg direction=\"in\" type=\"b\"/>\n"
"      <annotation value=\"WallpaperService::setMuteOnFullscreen\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"getAudioSettings\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"a{sv}\"/>\n"
"      <annotation value=\"WallpaperService::getAudioSettings\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"pause\"/>\n"
"    <method name=\"resume\"/>\n"
"    <method name=\"stop\"/>\n"
"    <method name=\"getLibrary\">\n"
"      <annotation value=\"QVariantList\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"a{sv}\"/>\n"
"      <annotation value=\"WallpaperService::getLibrary\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"scanLibrary\"/>\n"
"    <method name=\"addCustomLibraryPath\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <annotation value=\"WallpaperService::addCustomLibraryPath\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"registerTrustedDirectory\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <annotation value=\"WallpaperService::registerTrustedDirectory\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"getTrustedDirectories\">\n"
"      <annotation value=\"QStringList\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"as\"/>\n"
"      <annotation value=\"WallpaperService::getTrustedDirectories\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"getWallpaperProperties\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"a{sv}\"/>\n"
"      <annotation value=\"WallpaperService::getWallpaperProperties\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"setProperty\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <annotation value=\"QVariant\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"      <arg direction=\"in\" type=\"v\"/>\n"
"      <annotation value=\"WallpaperService::setProperty\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <method name=\"getProperty\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <annotation value=\"QVariant\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"v\"/>\n"
"      <annotation value=\"WallpaperService::getProperty\" name=\"org.qt.QtDBus.MethodAdaptor\"/>\n"
"    </method>\n"
"    <signal name=\"frameReady\"/>\n"
"    <signal name=\"wallpaperLoaded\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </signal>\n"
"    <signal name=\"libraryUpdated\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </signal>\n"
"    <signal name=\"bufferResized\">\n"
"      <arg direction=\"out\" type=\"u\"/>\n"
"      <arg direction=\"out\" type=\"u\"/>\n"
"    </signal>\n"
"    <signal name=\"propertyChanged\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"      <annotation value=\"QVariant\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"      <arg direction=\"out\" type=\"v\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    WallpaperServiceAdaptor(QObject *parent);
    virtual ~WallpaperServiceAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void addCustomLibraryPath(const QString &in0);
    QVariantList getAudioBands();
    QVariantMap getAudioSettings();
    QVariantList getAvailableGpus();
    QDBusUnixFileDescriptor getBufferFdForOutput(const QString &in0);
    QVariantMap getBufferInfo();
    QVariantMap getBufferInfoForOutput(const QString &in0);
    QVariantList getLibrary();
    QStringList getOutputs();
    QVariantList getPauseState();
    QDBusVariant getProperty(const QString &in0);
    QStringList getTrustedDirectories();
    QVariantMap getWallpaperProperties(const QString &in0);
    bool isOutputCovered(const QString &in0);
    bool isPauseAllOutputs();
    bool isPauseEnabled();
    bool isPauseMuteAudio();
    bool loadWallpaper(const QString &in0);
    bool loadWallpaperEphemeral(const QString &in0);
    void pause();
    double pauseCoverageThreshold();
    bool registerTrustedDirectory(const QString &in0);
    void requestFrame();
    void resume();
    void scanLibrary();
    void setAudioMuted(bool in0);
    void setAudioVolume(int in0);
    void setMousePosition(double in0, double in1);
    void setMuteOnFullscreen(bool in0);
    void setMuteOnOtherAudio(bool in0);
    void setPauseAllOutputs(bool in0);
    void setPauseCoverageThreshold(double in0);
    void setPauseEnabled(bool in0);
    void setPauseMuteAudio(bool in0);
    void setProperty(const QString &in0, const QDBusVariant &in1);
    bool setResolution(uint in0, uint in1);
    bool setResolutionForOutput(const QString &in0, uint in1, uint in2);
    bool startAudioCapture();
    void stop();
    void stopAudioCapture();
Q_SIGNALS: // SIGNALS
    void bufferResized(uint in0, uint in1);
    void frameReady();
    void libraryUpdated(int in0);
    void propertyChanged(const QString &in0, const QDBusVariant &in1);
    void wallpaperLoaded(const QString &in0);
};

#endif
