#!/usr/bin/env python3
"""Compile GLSL shaders to SPIR-V and embed them as C++ arrays.

Output: daemon/src/render/graphics_shaders_spv.h (quad/grain/particle
pipeline code). The compute .comp shaders keep their existing hand-embedded
blobs in shaders_spv.h; this script only (re)generates the graphics-pipeline
additions. Run from repo root whenever a .vert/.frag under
daemon/src/render/shaders/ changes:

  python3 daemon/src/render/shaders/embed_shaders.py
"""
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "graphics_shaders_spv.h"))

SHADERS = ["fullscreen.vert", "quad.vert", "quad.frag", "gpu_grain.frag", "particle.vert", "particle.frag"]


def compile_shader(src: str) -> list:
    spv = tempfile.NamedTemporaryFile(suffix=".spv", delete=False)
    spv.close()
    try:
        proc = subprocess.run(
            ["glslangValidator", "-V", os.path.join(HERE, src), "-o", spv.name],
            capture_output=True, text=True,
        )
        if proc.returncode != 0:
            raise RuntimeError(f"{src} failed to compile:\n{proc.stderr}")
        with open(spv.name, "rb") as f:
            data = f.read()
    finally:
        os.unlink(spv.name)
    words = [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]
    return words


def ident(src: str) -> str:
    return src.replace(".", "_").replace("/", "_")


def main() -> None:
    blocks = []
    for src in SHADERS:
        words = compile_shader(src)
        name = ident(src)
        lines = []
        for i in range(0, len(words), 8):
            chunk = ", ".join(f"0x{w:08x}u" for w in words[i:i + 8])
            lines.append("    " + chunk + ",")
        blocks.append(
            f"inline const std::vector<uint32_t> {name} = {{\n" + "\n".join(lines) + "\n};"
        )
        print(f"  {src}: {len(words)} words")

    header = (
        "#pragma once\n"
        "#include <vector>\n"
        "#include <cstdint>\n"
        "namespace WallpaperEngine::Render::Shaders {\n"
        "// Graphics-pipeline SPIR-V blobs, generated by shaders/embed_shaders.py.\n"
        "// Do not edit by hand.\n\n"
        + "\n\n".join(blocks)
        + "\n\n} // namespace WallpaperEngine::Render::Shaders\n"
    )
    with open(OUT, "w") as f:
        f.write(header)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    sys.exit(main())
